export const copy = {
  searchFields: ['搜索字段', 'Search fields'], toolSections: ['工具分区', 'Tool sections'], selectSection: ['选择与排序', 'Select & sort'], cleanSection: ['清洗', 'Clean'], transformSection: ['转换', 'Transform'], groupSection: ['分组', 'Group'], joinSection: ['关联', 'Join'], timeSection: ['时间', 'Time'], visualSection: ['可视化', 'Visualize'],
  missingTools: ['缺失值', 'Missing values'], duplicateTools: ['重复值', 'Duplicates'], selectTools: ['数据选择', 'Selection'], sortTools: ['排列', 'Ordering'], analysisTools: ['统计', 'Statistics'], chartsTools: ['图形', 'Charts'], more: ['更多', 'More'],
  cancel: ['取消', 'Cancel'], currentTool: ['当前工具', 'Current tool'], previewReady: ['操作预览', 'Operation preview'], previewUpdating: ['正在更新预览…', 'Updating preview…'], previewPending: ['等待有效参数后预览', 'Preview awaits valid parameters'], applied: ['已应用', 'Applied'], compare: ['对比', 'Compare'], resultBefore: ['操作前', 'Before'], resultAfter: ['操作后', 'After'], collapseSidebar: ['收起侧栏', 'Hide sidebar'], expandSidebar: ['展开侧栏', 'Show sidebar'],
  keepSelected: ['保留选中', 'Keep selected'], excludeSelected: ['排除选中', 'Exclude selected'], temporarySelection: ['临时选择', 'Temporary selection'], selectionHint: ['图形选择只用于探索；保留或排除选中后才改变数据。', 'Chart selections are exploratory. Keep or exclude the selection to change data.'],
  viewingHistory: ['正在查看历史步骤', 'Viewing a historical step'], returnLatest: ['返回当前分析', 'Return to current analysis'], continueHere: ['从此步骤继续', 'Continue from this step'], historyReadOnly: ['历史查看不会修改当前分析。继续时会保留原分支。', 'Viewing history does not change your analysis. Continuing preserves the previous branch.'], branches: ['保留的分支', 'Saved branches'], branch: ['分析分支', 'Analysis branch'], restoreBranch: ['切换至此分支', 'Switch to this branch'], readonlyTool: ['请返回当前分析，或从此步骤继续后使用工具。', 'Return to your analysis or continue from this step to use tools.'],
  matchesCount: ['匹配记录', 'Matched rows'], unmatchedCount: ['未匹配记录', 'Unmatched rows'], outputRows: ['输出行数', 'Output rows'], invalidPreview: ['请修正参数后再应用。', 'Correct the parameters before applying.'], selectFieldHint: ['点击字段可填入当前工具；多字段可按 Ctrl / ⌘ 选择。', 'Click a field to use it in the tool; Ctrl / ⌘ selects multiple fields.'], chartLocked: ['这是操作结果预览。应用或取消后可继续通过图形选择数据。', 'This is a result preview. Apply or cancel to resume chart selection.'],
  quality: ['质量检查', 'Quality check'], summaryTool: ['字段摘要', 'Field summary'], overviewTool: ['联动探索', 'Linked exploration'], sortHint: ['排序也先预览；点击表头可选择排序字段。', 'Sorting is previewed first; click a header to choose a field.'], chartSettings: ['图形设置', 'Chart settings'],
  missingChanged: ['缺失值变化', 'Missing-value change'], rowsChanged: ['记录变化', 'Row change'], columnsChanged: ['字段变化', 'Column change'],

  title: ['数据织坊', 'Data Loom'], subtitle: ['从原始数据，织出清晰洞见。', 'Weave raw data into clear insights.'],
  intro: ['加载、探索、清洗和分析。每一个结果，都有迹可循。', 'Load, explore, clean, and analyze. Every result has a traceable path.'],
  import: ['导入数据', 'Import data'], export: ['导出 CSV', 'Export CSV'], backup: ['备份工作区', 'Back up workspace'], restore: ['恢复备份', 'Restore backup'],
  overview: ['概述', 'Overview'], data: ['数据表', 'Data table'], clean: ['数据体检', 'Data quality'], analyze: ['分组与透视', 'Group & pivot'], join: ['关联与计算', 'Join & calculate'],
  datasets: ['数据集', 'Datasets'], fields: ['字段', 'Fields'], rows: ['行', 'rows'], columns: ['列', 'columns'], missing: ['缺失单元格', 'Missing cells'], duplicates: ['重复记录', 'Duplicate rows'],
  numeric: ['数值字段', 'Numeric fields'], number: ['数值', 'Number'], text: ['文本', 'Text'], date: ['日期', 'Date'], boolean: ['布尔', 'Boolean'], empty: ['空列', 'Empty'],
  sample: ['教学合成数据 · 固定种子生成，包含缺失、重复和异常记录。', 'Synthetic teaching data · seeded, with missing values, duplicates, and outliers.'],
  local: ['数据在浏览器处理，工作区自动保存到此浏览器。', 'Data is processed in your browser. This workspace saves locally.'],
  loading: ['正在恢复工作区…', 'Restoring workspace…'], saving: ['正在保存…', 'Saving…'], saved: ['已保存到此浏览器', 'Saved in this browser'], unsaved: ['尚未保存', 'Not saved'], restored: ['已恢复上次分析', 'Previous analysis restored'],
  distribution: ['数值分布', 'Numeric distribution'], categories: ['类别比较', 'Category comparison'], relationship: ['数值关系', 'Numeric relationship'],
  chartHint: ['点击柱形选择区间或类别；框选散点探索记录。', 'Click bars to select a range or category; brush points to explore records.'],
  selected: ['已选中', 'Selected'], clearFilters: ['清除选择', 'Clear selection'], applyFilters: ['应用筛选', 'Apply filters'], filter: ['筛选', 'Filter'],
  all: ['全部记录', 'All records'], condition: ['条件', 'Condition'], addFilter: ['添加条件', 'Add condition'], column: ['字段', 'Column'], operator: ['条件类型', 'Operator'], value: ['值', 'Value'],
  eq: ['等于', 'Equals'], contains: ['包含文本', 'Contains text'], gte: ['大于等于', 'At least'], lte: ['小于等于', 'At most'], present: ['非空', 'Not missing'],
  missingOp: ['为空', 'Is missing'], range: ['区间', 'Range'], and: ['满足全部条件', 'Match all conditions'], or: ['满足任一条件', 'Match any condition'],
  x: ['横轴', 'X axis'], y: ['纵轴', 'Y axis'], category: ['类别字段', 'Category field'], metric: ['数值指标', 'Numeric metric'],
  noNumeric: ['此数据没有可用数值字段。可查看类别分布和数据表。', 'No numeric fields available. Explore categories and the data table.'],
  noCategory: ['没有适合的类别字段（唯一值超过 60）。', 'No suitable category field (more than 60 unique values).'],
  noRows: ['没有符合条件的记录。清除选择或撤销操作。', 'No matching records. Clear selection or undo an operation.'],
  qualityTitle: ['先看见问题，再决定如何处理', 'See the issue before choosing a treatment'], qualityHint: ['异常值需要结合业务判断；本页不会自动删除异常记录。', 'Outliers need domain judgment; they are not automatically removed.'],
  qualityMap: ['缺失矩阵', 'Missing-value matrix'], qualityMapHint: ['显示前 100 行；橙色表示缺失，统计基于全量数据。', 'First 100 rows shown; orange indicates missing. Statistics use all rows.'],
  cleanTitle: ['清洗操作', 'Cleaning operation'], method: ['处理方式', 'Method'], fill: ['填充缺失值', 'Fill missing values'], dropMissing: ['删除字段缺失的行', 'Drop rows missing this field'], dedup: ['删除完全重复的行', 'Drop exact duplicate rows'],
  constant: ['指定值', 'Constant'], mean: ['均值', 'Mean'], median: ['中位数', 'Median'], sum: ['求和', 'Sum'], count: ['非空计数', 'Non-null count'], nunique: ['唯一值数', 'Unique count'], min: ['最小值', 'Minimum'], max: ['最大值', 'Maximum'], std: ['标准差', 'Sample standard deviation'],
  preview: ['预览变化', 'Preview changes'], apply: ['应用操作', 'Apply operation'], before: ['操作前', 'Before'], after: ['操作后', 'After'], missingCount: ['缺失数', 'Missing count'],
  grouping: ['构建分组分析', 'Build a grouped analysis'], group: ['分组字段', 'Group by'], aggregate: ['聚合方式', 'Aggregation'], groupMode: ['分析模式', 'Analysis mode'], groupSimple: ['分组统计', 'Group summary'], pivot: ['透视表', 'Pivot table'], month: ['按月汇总', 'Monthly summary'], pivotColumn: ['透视列字段', 'Pivot columns'],
  groupHint: ['选择维度和指标，先预览，再写入操作时间线。', 'Choose a dimension and metric. Preview before adding to the timeline.'],
  joinTitle: ['关联另一张表', 'Join another table'], rightTable: ['右侧数据集', 'Right dataset'], leftKey: ['左表关联键', 'Left key'], rightKey: ['右表关联键', 'Right key'], how: ['关联方式', 'Join type'], left: ['左关联：保留左表记录', 'Left: keep all left rows'], inner: ['内关联：只保留匹配记录', 'Inner: keep matches'],
  joinHint: ['预览实际输出行数；重复关联键可能让行数增加。空键按同值匹配。', 'Preview the actual row count; duplicate keys can expand rows. Null keys match null keys.'],
  calculate: ['创建计算列', 'Create a calculated column'], newColumn: ['新字段名', 'New column name'], leftField: ['左侧数值字段', 'Left numeric field'], rightField: ['右侧数值字段', 'Right numeric field'], arithmetic: ['运算', 'Arithmetic'], calculateHint: ['缺失值传播；除以零的结果记为缺失。', 'Missing values propagate; division by zero produces a missing value.'],
  history: ['操作时间线', 'Operation timeline'], original: ['原始数据', 'Original data'], undo: ['撤销', 'Undo'], redo: ['重做', 'Redo'], reset: ['恢复示例', 'Open example'],
  sort: ['排序', 'Sort'], ascending: ['升序', 'Ascending'], descending: ['降序', 'Descending'], page: ['页', 'Page'], previous: ['上一页', 'Previous'], next: ['下一页', 'Next'], tableHint: ['每页 50 行。点击字段标题排序；缺失值始终排在末尾。', '50 rows per page. Click headers to sort; missing values stay last.'],
  summary: ['字段摘要', 'Field summary'], unique: ['唯一值', 'Unique'], missingRate: ['缺失率', 'Missing %'], details: ['详情', 'Details'],
  importTitle: ['加载你的数据', 'Load your data'], importHint: ['CSV、TSV 或对象数组 JSON，单文件最多 10 MB。支持一次选择多份文件。', 'CSV, TSV, or JSON arrays of objects, up to 10 MB per file. Select multiple files at once.'],
  chooseFile: ['选择文件或拖到这里', 'Choose files or drop them here'], encoding: ['CSV / TSV 编码', 'CSV / TSV encoding'], delimiter: ['CSV 分隔符', 'CSV delimiter'], comma: ['逗号', 'Comma'], semicolon: ['分号', 'Semicolon'], tab: ['制表符', 'Tab'], paste: ['或粘贴 CSV 文本', 'Or paste CSV text'], loadPaste: ['加载文本', 'Load text'], close: ['关闭', 'Close'],
  storage: ['本地保存', 'Local storage'], storageHint: ['可清理本地数据，或下载备份到其他浏览器恢复。备份包含原始数据。', 'Clear local data or download a backup to restore in another browser. Backups include source data.'],
  autoSave: ['自动保存', 'Autosave'], retry: ['重试保存', 'Retry save'], clearStorage: ['清除本地工作区', 'Clear local workspace'], clearConfirm: ['清除本地保存并打开示例？建议先下载备份。', 'Clear local storage and open the example? Download a backup first.'], resetConfirm: ['打开示例将替换当前工作区。需要保留时请先下载备份。继续？', 'Opening the example replaces this workspace. Back up first to keep it. Continue?'],
  capacity: ['本站存储占用', 'Site storage usage'], temporary: ['临时模式 · 关闭页面后未保存修改将丢失', 'Temporary mode · unsaved changes are lost when closing'],
  storageConflict: ['另一标签页已更新工作区。请先备份本页，再刷新加载最新版本。', 'Another tab updated this workspace. Back up this page, then reload the latest version.'],
  storageQuota: ['本地空间不足。当前分析仍在内存中，请下载备份。', 'Local storage is full. Analysis is still in memory; download a backup.'],
  storageFailed: ['本地保存失败。请重试或下载备份。', 'Local saving failed. Retry or download a backup.'], storageCorrupt: ['本地数据不完整。请恢复备份或重新导入。', 'Local data is incomplete. Restore a backup or import again.'], storageBlocked: ['其他标签页阻止打开存储，请关闭后重试。', 'Another tab blocked storage. Close it and retry.'],
  workspaceLimit: ['工作区最多 20 个数据集，原始文件总量最多 20 MB。请备份后新建分析。', 'A workspace supports up to 20 datasets and 20 MB of source files. Back up before starting a new analysis.'],
  invalidDate: ['按月汇总需要有效的日期字段。', 'Monthly summary requires a valid date field.'],
  emptyFile: ['文件没有数据记录。', 'The file contains no data rows.'], csvInvalid: ['CSV 引号格式不正确，请检查文件。', 'Invalid CSV quoting. Check the file.'], rowWidth: ['CSV 行的列数不一致，请检查分隔符和数据。', 'CSV rows have inconsistent widths. Check the delimiter and data.'],
  duplicateColumns: ['字段名为空、重复或与已有字段冲突。', 'Column names are empty, duplicated, or conflict with existing columns.'], jsonInvalid: ['JSON 必须是非空的对象数组。', 'JSON must be a nonempty array of objects.'], nestedJson: ['此版本不支持嵌套 JSON，请先展开对象。', 'Nested JSON is not supported yet. Flatten the objects first.'],
  invalidNumber: ['请使用有效数值和数值字段。', 'Use valid numbers and numeric fields.'], noValues: ['没有可用于填充的有效值。', 'No valid values available for filling.'], missingColumn: ['操作引用的字段不存在。', 'A referenced column is missing.'], missingDataset: ['关联数据集不存在。', 'The join dataset is missing.'], invalidOperation: ['操作无法执行，请检查参数。', 'Cannot execute this operation. Check the parameters.'],
  tooManyCategories: ['透视列最多支持 60 个类别，请先筛选。', 'Pivot supports up to 60 categories. Filter first.'], tooManyRows: ['数据超过处理范围：最多 100,000 行、200 列和 200 万单元格。请先拆分数据。', 'Processing limit: 100,000 rows, 200 columns, and 2 million cells. Split the data first.'],
  fileTooLarge: ['文件超过 10 MB，请先拆分数据。', 'File exceeds 10 MB. Split the data first.'], unsupported: ['请选择 CSV、TSV 或 JSON 文件。', 'Choose a CSV, TSV, or JSON file.'], backupInvalid: ['备份格式、版本或操作记录无效。', 'Invalid backup format, version, or operations.'],
  busy: ['正在计算…', 'Computing…'], samplePoints: ['最多显示 1,500 个点，统计与筛选基于全部记录。', 'Up to 1,500 points displayed; statistics and filters use all rows.'],
  readme: ['第一版支持本地分析；尚未提供 XLSX、在线地址加载和 pandas 脚本导出。', 'This version supports local analysis; XLSX, URL loading, and pandas script export are not available yet.'],
} as const;
export type Key = keyof typeof copy;
export function t(key: Key, en = document.documentElement.lang === 'en'): string { return (copy[key] ?? copy.invalidOperation)[en ? 1 : 0]; }
